/**
 * Generators for the evidence map (JSON + HTML), review checklist (Markdown +
 * HTML), run record (JSON), and provenance page (HTML). All paths written
 * into artifacts are relative to the example directory so the exports contain
 * no local absolute paths.
 *
 * The three HTML pages (Evidence, Review_Checklist, Provenance) are the
 * buyer-facing surfaces published on the website: business language only —
 * no raw identifiers as primary labels, no developer vocabulary. The JSON and
 * Markdown artifacts remain the machine-readable record in output/.
 *
 * Illustrative workflow — synthetic data.
 */
import * as fs from "node:fs";
import * as path from "node:path";
import {
  ClaimRecord,
  INPUT_FILES,
  LABEL,
  MemoContent,
  OUTPUT,
  ReviewStatus,
  SourceRecord,
  SourceRegistry,
  loadChecklist,
  loadWorkflowMeta,
  officecliVersion,
  p,
  sha256,
} from "./lib.ts";

export interface EvidenceClaim extends ClaimRecord {
  sources: SourceRecord[];
}

export interface EvidenceMap {
  label: string;
  workflow: string;
  workflow_version: string;
  company: string;
  as_of: string;
  lineage_note: string;
  summary: {
    sources_reviewed: number;
    sources_excluded: number;
    claims_total: number;
    figures_flagged: number;
  };
  claims: EvidenceClaim[];
  excluded_sources: SourceRecord[];
}

const FLAGGED_STATUSES: ReviewStatus[] = ["needs_analyst", "flagged", "unresolved"];

export function buildEvidenceMap(memo: MemoContent, registry: SourceRegistry): EvidenceMap {
  const byId = new Map(registry.sources.map((s) => [s.source_id, s]));
  const approved = registry.sources.filter((s) => s.approved);
  const excluded = registry.sources.filter((s) => !s.approved);
  const claims: EvidenceClaim[] = memo.claims.map((c) => ({
    ...c,
    sources: c.source_ids.map((id) => {
      const s = byId.get(id);
      if (!s) throw new Error(`claim ${c.claim_id} references unknown source ${id}`);
      return s;
    }),
  }));
  return {
    label: LABEL,
    workflow: memo.workflow,
    workflow_version: memo.workflow_version,
    company: memo.company,
    as_of: memo.as_of,
    lineage_note:
      "Cell-level lineage is demonstrated only for Excel-sourced figures (sheet+cell re-read by the acceptance checks). Filing, transcript, note, and CSV references are section- or page-level.",
    summary: {
      sources_reviewed: approved.length,
      sources_excluded: excluded.length,
      claims_total: claims.length,
      figures_flagged: claims.filter((c) => FLAGGED_STATUSES.includes(c.review_status)).length,
    },
    claims,
    excluded_sources: excluded,
  };
}

// ---------------------------------------------------------------------------
// Shared HTML building blocks (buyer-facing visual language)
// ---------------------------------------------------------------------------

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

/** Buyer-facing footer sentence shared by all three published pages. */
const PAGE_FOOTER =
  "Illustrative workflow — synthetic data. Not client work. Generated by an open-source workflow foundation.";

const SHARED_CSS = `
  :root { color-scheme: light; }
  * { box-sizing: border-box; }
  body { margin: 0; background: #fcfbf9; color: #1c1c1e;
         font: 16px/1.6 system-ui, -apple-system, "Segoe UI", Helvetica, Arial, sans-serif;
         -webkit-font-smoothing: antialiased; }
  .wrap { max-width: 760px; margin: 0 auto; padding: 56px 24px 48px; }
  .eyebrow { margin: 0 0 10px; font-size: 12px; font-weight: 700; letter-spacing: 0.14em;
             text-transform: uppercase; color: #8a8478; }
  h1 { margin: 0 0 14px; font-size: 30px; line-height: 1.2; font-weight: 700; color: #1b365d;
       letter-spacing: -0.01em; }
  .badge { display: inline-block; border: 1px solid #ddd5c2; background: #f4f0e5; color: #57513f;
           border-radius: 999px; padding: 5px 14px; font-size: 12.5px; font-weight: 600;
           letter-spacing: 0.01em; }
  .lede { margin: 18px 0 0; font-size: 15.5px; color: #55534e; max-width: 640px; }
  h2 { margin: 44px 0 16px; font-size: 19px; font-weight: 700; color: #1b365d; letter-spacing: -0.005em; }
  .section-note { margin: -8px 0 16px; font-size: 14px; color: #6d6a63; max-width: 620px; }
  .stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; margin: 28px 0 8px; }
  .stat { background: #fff; border: 1px solid #e8e3d8; border-radius: 12px; padding: 14px 16px; }
  .stat .n { font-size: 24px; font-weight: 700; color: #1b365d; line-height: 1.2; }
  .stat .t { margin-top: 3px; font-size: 11.5px; font-weight: 600; letter-spacing: 0.06em;
             text-transform: uppercase; color: #8a8478; }
  .card { background: #fff; border: 1px solid #e8e3d8; border-radius: 12px;
          padding: 18px 22px; margin: 0 0 12px; }
  .card-top { display: flex; align-items: flex-start; justify-content: space-between; gap: 14px; }
  .claim-text { margin: 0; font-size: 16.5px; line-height: 1.5; font-weight: 600; color: #1c1c1e; }
  .pill { display: inline-block; border-radius: 999px; padding: 3px 12px; font-size: 12px;
          font-weight: 700; letter-spacing: 0.01em; white-space: nowrap; flex: none; margin-top: 2px; }
  .pill.good { background: #e6f1e9; color: #1e6b41; }
  .pill.warn { background: #f8efd9; color: #8a5a10; }
  .pill.stop { background: #f9e7e5; color: #a02c22; }
  .pill.navy { background: #e8edf4; color: #1b365d; }
  .pill.mute { background: #f0ede4; color: #57513f; }
  .src { margin: 10px 0 0; font-size: 14px; color: #55534e; }
  .src strong { color: #1c1c1e; font-weight: 600; }
  .quote { margin: 10px 0 0; padding: 8px 14px; border-left: 3px solid #d8d2c2;
           font-size: 14px; color: #6d6a63; font-style: italic; }
  .verify { margin: 12px 0 0; padding: 10px 14px; border-radius: 8px; background: #faf4e3;
            border: 1px solid #ecdfba; font-size: 14px; color: #6b4f10; }
  .verify strong { color: #58400a; }
  .meta { margin: 12px 0 0; font-size: 11.5px; color: #a39d8f; }
  .hash { margin: 8px 0 0; font-size: 11px; color: #a39d8f; word-break: break-all; }
  .foot { margin-top: 52px; border-top: 1px solid #e8e3d8; padding-top: 18px;
          font-size: 13px; color: #8a8478; }
  .foot p { margin: 0 0 8px; }
  @media (max-width: 620px) { .stats { grid-template-columns: repeat(2, 1fr); }
    .card-top { flex-direction: column; gap: 8px; } }
`;

interface PageOpts {
  title: string;
  eyebrow: string;
  heading: string;
  lede?: string;
  extraCss?: string;
  body: string;
  footNote?: string;
}

function renderPage(o: PageOpts): string {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(o.title)}</title>
<style>${SHARED_CSS}${o.extraCss ?? ""}</style>
</head>
<body>
<div class="wrap">
  <header>
    <p class="eyebrow">${esc(o.eyebrow)}</p>
    <h1>${esc(o.heading)}</h1>
    <p><span class="badge">${esc(LABEL)} · Draft for review</span></p>
    ${o.lede ? `<p class="lede">${esc(o.lede)}</p>` : ""}
  </header>
${o.body}
  <footer class="foot">
    ${o.footNote ? `<p>${esc(o.footNote)}</p>` : ""}
    <p>${esc(PAGE_FOOTER)}</p>
  </footer>
</div>
</body>
</html>
`;
}

// --- buyer-language helpers --------------------------------------------------

const SOURCE_TYPE_LABELS: Record<SourceRecord["source_type"], string> = {
  excel_model: "Excel model",
  filing: "Public filing excerpt",
  transcript: "Earnings call transcript",
  internal_note: "Internal note",
  vendor_export: "Data export",
  web: "Web source",
  template: "Template",
};

function formatNumber(raw: string): string {
  const n = Number(raw);
  return Number.isFinite(n) ? n.toLocaleString("en-US") : raw;
}

/** One source, phrased for a business reader. */
function sourceLine(s: SourceRecord): string {
  const typeLabel = SOURCE_TYPE_LABELS[s.source_type] ?? "Source";
  const base = path.basename(s.file);
  const bits: string[] = [];
  if (s.location.sheet && s.location.cell) {
    bits.push(base, `${s.location.sheet} sheet`, `cell ${s.location.cell}`);
    if (s.extracted_value) bits.push(`value ${formatNumber(s.extracted_value)}`);
  } else {
    if (s.source_type === "vendor_export") bits.push(base);
    if (s.location.section && s.location.section !== "n/a") bits.push(s.location.section);
    if (s.location.page !== undefined && !s.location.section?.toLowerCase().includes("section")) {
      bits.push(`page ${s.location.page}`);
    }
  }
  const detail = bits.length > 0 ? ` — ${bits.map(esc).join(" · ")}` : "";
  return `<strong>${esc(typeLabel)}</strong>${detail} <span style="color:#a39d8f">· as of ${esc(s.as_of)}</span>`;
}

/** Plain-language status pill for a claim. */
function claimPill(c: ClaimRecord): { cls: string; text: string } {
  switch (c.review_status) {
    case "verified":
      return c.relationship === "derived"
        ? { cls: "good", text: "Derived — verified" }
        : { cls: "good", text: "Sourced" };
    case "needs_analyst":
      return c.relationship === "derived"
        ? { cls: "warn", text: "Derived — needs analyst" }
        : { cls: "warn", text: "Needs analyst" };
    case "flagged":
      return { cls: "warn", text: "Sourced — verify before use" };
    case "unresolved":
      return { cls: "stop", text: "Unresolved — escalate" };
  }
}

/** Plain-language names for the standing acceptance checks (buyer surfaces). */
const CHECK_FRIENDLY: Record<string, string> = {
  "sections-present": "All six memo sections are present, in order",
  "docx-validates": "The Word document passes format validation",
  "no-placeholder-text": "No placeholder or template text remains in the memo",
  "claims-have-sources": "Every quantitative figure is sourced or explicitly flagged",
  "excel-cell-verification": "Excel-sourced figures re-checked against the model's actual cells",
  "table-matches-evidence": "The memo's financial table matches the evidence report",
  "unresolved-in-checklist": "Unresolved items appear on the reviewer checklist",
  "run-record-complete": "Inputs, exclusions, and review status are fully recorded",
};

function friendlyCheckName(id: string): string {
  return CHECK_FRIENDLY[id] ?? loadChecklist().find((c) => c.id === id)?.name ?? id;
}

// ---------------------------------------------------------------------------
// Evidence report (HTML)
// ---------------------------------------------------------------------------

export function renderEvidenceHtml(ev: EvidenceMap): string {
  const unresolvedCount = ev.claims.filter((c) => c.review_status === "unresolved").length;

  const claimCards = ev.claims
    .map((c) => {
      const pill = claimPill(c);
      const sources = c.sources.map((s) => `<p class="src">${sourceLine(s)}</p>`).join("\n      ");
      const excerpts = c.sources
        .filter((s) => s.excerpt)
        .map((s) => `<p class="quote">&ldquo;${esc(s.excerpt!)}&rdquo;</p>`)
        .join("\n      ");
      const derived =
        c.verification?.type === "excel_derived"
          ? `<p class="src">How it is derived: ${esc(c.verification.derivation)}.</p>`
          : "";
      return `  <article class="card">
    <div class="card-top">
      <p class="claim-text">&ldquo;${esc(c.rendered_text)}&rdquo;</p>
      <span class="pill ${pill.cls}">${esc(pill.text)}</span>
    </div>
      ${sources}
      ${derived}
      ${excerpts}
      ${c.review_note ? `<p class="verify"><strong>What to verify:</strong> ${esc(c.review_note)}</p>` : ""}
      <p class="meta">Reference ${esc(c.claim_id)}</p>
  </article>`;
    })
    .join("\n");

  const excluded = ev.excluded_sources
    .map(
      (s) => `  <article class="card">
    <div class="card-top">
      <p class="claim-text">${esc(s.title)}</p>
      <span class="pill mute">Excluded — source policy</span>
    </div>
    <p class="src">${esc(s.exclusion_reason ?? "Excluded before drafting.")}</p>
    <p class="meta">Reference ${esc(s.source_id)}</p>
  </article>`,
    )
    .join("\n");

  const body = `
  <div class="stats">
    <div class="stat"><div class="n">${ev.summary.sources_reviewed}</div><div class="t">Sources reviewed</div></div>
    <div class="stat"><div class="n">${ev.summary.claims_total}</div><div class="t">Claims tracked</div></div>
    <div class="stat"><div class="n">${ev.summary.figures_flagged}</div><div class="t">Figures to verify</div></div>
    <div class="stat"><div class="n">${unresolvedCount}</div><div class="t">Unresolved</div></div>
  </div>
  <h2>Every claim, with its source</h2>
  <p class="section-note">Each figure or statement used in the memo appears below with where it came
  from and its review status. Nothing in the draft is unaccounted for.</p>
${claimCards}
  <h2>Excluded from this draft</h2>
  <p class="section-note">Candidate material rejected at source review. No claim in the memo relies on it.</p>
${excluded}`;

  return renderPage({
    title: "Project Alder — Evidence report",
    eyebrow: "Project Alder · Synthetic company · As of " + ev.as_of,
    heading: "Project Alder — Evidence report",
    lede:
      "Every key figure and claim in the draft memo, with its source and review status. " +
      "A reviewer works through the flagged items before sign-off.",
    body,
    footNote:
      "Cell-level tracing applies to the Excel-sourced figures, which are re-checked against the " +
      "model's actual cells on every run. Filing, transcript, note, and CSV references are section- " +
      "or page-level. All data on this page is synthetic and the draft carries no reviewer sign-off.",
  });
}

// ---------------------------------------------------------------------------
// Reviewer checklist (HTML)
// ---------------------------------------------------------------------------

const CHECKLIST_CSS = `
  .check-item { display: flex; gap: 14px; background: #fff; border: 1px solid #e8e3d8;
                border-radius: 12px; padding: 16px 20px; margin: 0 0 10px; }
  .box { flex: none; width: 20px; height: 20px; margin-top: 2px; border: 2px solid #b9b2a1;
         border-radius: 5px; background: #fcfbf9; }
  .check-item.urgent { border: 1px solid #e5b8b2; border-left: 5px solid #a02c22; background: #fffAf9; }
  .check-item.urgent .box { border-color: #a02c22; }
  .item-head { display: flex; align-items: flex-start; justify-content: space-between; gap: 12px; }
  .item-body { flex: 1; min-width: 0; }
  .standing { display: flex; gap: 12px; align-items: baseline; background: #fff;
              border: 1px solid #e8e3d8; border-radius: 10px; padding: 11px 18px; margin: 0 0 8px;
              font-size: 14.5px; color: #1c1c1e; }
  .tick { flex: none; color: #1e6b41; font-weight: 700; }
`;

export function renderReviewChecklistHtml(ev: EvidenceMap): string {
  const attention = ev.claims.filter(
    (c) => c.review_status === "needs_analyst" || c.review_status === "flagged",
  );
  const unresolved = ev.claims.filter((c) => c.review_status === "unresolved");

  const item = (c: EvidenceClaim, urgent: boolean): string => {
    const pill = claimPill(c);
    const title = c.table?.metric ?? c.rendered_text;
    const sources = c.sources.map((s) => `<p class="src">${sourceLine(s)}</p>`).join("\n        ");
    return `  <div class="check-item${urgent ? " urgent" : ""}">
    <span class="box" aria-hidden="true"></span>
    <div class="item-body">
      <div class="item-head">
        <p class="claim-text">${esc(title)}</p>
        <span class="pill ${pill.cls}">${esc(pill.text)}</span>
      </div>
      <p class="src" style="margin-top:6px">The memo states: &ldquo;${esc(c.rendered_text)}&rdquo;</p>
        ${sources}
      ${c.review_note ? `<p class="verify"><strong>What to verify:</strong> ${esc(c.review_note)}</p>` : ""}
      <p class="meta">Reference ${esc(c.claim_id)}</p>
    </div>
  </div>`;
  };

  const standing = loadChecklist()
    .map((c) => `  <div class="standing"><span class="tick">✓</span><span>${esc(friendlyCheckName(c.id))}</span></div>`)
    .join("\n");

  const body = `
  <h2>Figures to verify (${attention.length})</h2>
  <p class="section-note">Confirm each of these before the committee relies on the draft.</p>
${attention.map((c) => item(c, false)).join("\n")}
  <h2>Unresolved — must be resolved or escalated (${unresolved.length})</h2>
  <p class="section-note">The draft cannot be signed off while this item is open.</p>
${unresolved.map((c) => item(c, true)).join("\n")}
  <h2>Standing checks</h2>
  <p class="section-note">Enforced automatically on every run, before the draft reaches a reviewer.</p>
${standing}`;

  return renderPage({
    title: "Project Alder — Reviewer checklist",
    eyebrow: "Project Alder · Synthetic company · As of " + ev.as_of,
    heading: "Reviewer checklist",
    lede:
      `${attention.length + unresolved.length} items need a human decision before sign-off. ` +
      "Every claim in the draft remains a draft until a reviewer has worked through this list.",
    extraCss: CHECKLIST_CSS,
    body,
    footNote:
      "Review status: draft for review — no reviewer decision is recorded on any item yet. " +
      "All data on this page is synthetic.",
  });
}

// ---------------------------------------------------------------------------
// Provenance page — "What informed this draft" (HTML)
// ---------------------------------------------------------------------------

/** Friendly names + one-line descriptions for the committed input files. */
const INPUT_META: Record<string, { name: string; desc: string }> = {
  "inputs/Model_v12.xlsx": {
    name: "Excel model — Model_v12.xlsx",
    desc: "The operating model behind the memo's figures: the revenue build and P&L the verified numbers are read from.",
  },
  "inputs/10q-excerpt.md": {
    name: "Public filing excerpt — 10-Q",
    desc: "Condensed income statement and management discussion, used for revenue growth and margin guidance.",
  },
  "inputs/earnings-call-q2-transcript.md": {
    name: "Earnings call transcript — Q2 FY2025",
    desc: "Management remarks on customer concentration and net revenue retention.",
  },
  "inputs/internal-model-note.md": {
    name: "Internal note — financing assumptions",
    desc: "Analyst working note carrying the net-leverage assumption, marked not yet confirmed.",
  },
  "inputs/comps.csv": {
    name: "Comparable transactions export — comps.csv",
    desc: "Vendor-style export of eight comparable vertical-software transactions.",
  },
};

export interface CheckOutcome {
  id: string;
  pass: boolean;
}

export function renderProvenanceHtml(ev: EvidenceMap, outcomes: CheckOutcome[]): string {
  const wf = loadWorkflowMeta();

  const inputs = INPUT_FILES.map((f) => {
    const meta = INPUT_META[f] ?? { name: path.basename(f), desc: "Input file." };
    return `  <article class="card">
    <p class="claim-text">${esc(meta.name)}</p>
    <p class="src">${esc(meta.desc)}</p>
    <p class="hash">Fingerprint (SHA-256): ${sha256(p(f))}</p>
  </article>`;
  }).join("\n");

  const template = `  <article class="card">
    <p class="claim-text">Memo template — firm style</p>
    <p class="src">The Word template the memo is rendered into: house styles, standing title, and the labeled footer on every page.</p>
    <p class="hash">Fingerprint (SHA-256): ${sha256(p("template/ic-memo-template.docx"))}</p>
  </article>`;

  const excluded = ev.excluded_sources
    .map(
      (s) => `  <article class="card">
    <div class="card-top">
      <p class="claim-text">${esc(s.title)}</p>
      <span class="pill mute">Excluded</span>
    </div>
    <p class="src">${esc(s.exclusion_reason ?? "Excluded before drafting.")}</p>
  </article>`,
    )
    .join("\n");

  const checks = outcomes
    .map(
      (o) => `  <div class="standing"><span class="pill ${o.pass ? "good" : "stop"}">${o.pass ? "Pass" : "Fail"}</span><span>${esc(friendlyCheckName(o.id))}</span></div>`,
    )
    .join("\n");

  const body = `
  <h2>Inputs used</h2>
  <p class="section-note">The draft was produced from these files and nothing else. Each carries a
  cryptographic fingerprint so the exact versions used can always be confirmed.</p>
${inputs}
${template}
  <h2>Sources excluded</h2>
  <p class="section-note">Candidate material rejected under the source policy before drafting began.</p>
${excluded}
  <h2>How it was verified</h2>
  <p class="section-note">${outcomes.length} acceptance checks ran against the finished draft. Each one
  reads the produced documents back independently — none of them trust the drafting step's own bookkeeping.</p>
${checks}
  <h2>Workflow</h2>
  <article class="card">
    <div class="card-top">
      <p class="claim-text">Investment committee memo</p>
      <span class="pill navy">Draft for human review</span>
    </div>
    <p class="src">Workflow ${esc(wf.name)}, version ${esc(wf.version)}. Runs entirely from the approved
    files above — no network access and no credentials. A named reviewer signs the document; nothing is
    delivered without human sign-off.</p>
  </article>`;

  return renderPage({
    title: "Project Alder — What informed this draft",
    eyebrow: "Project Alder · Synthetic company · As of " + ev.as_of,
    heading: "What informed this draft",
    lede:
      "The provenance record for the draft memo: the inputs it used, the material it excluded, " +
      "and the checks it passed before reaching a reviewer.",
    body,
    footNote:
      "Cell-level tracing applies to the Excel-sourced figures; other references are section- or " +
      "page-level. All data on this page is synthetic and the draft carries no reviewer sign-off.",
  });
}

// ---------------------------------------------------------------------------
// Review checklist (markdown — machine artifact, kept alongside the HTML)
// ---------------------------------------------------------------------------

function mdSourceLocation(s: SourceRecord): string {
  if (s.location.sheet && s.location.cell) return `${s.location.sheet}!${s.location.cell}`;
  const bits: string[] = [];
  if (s.location.section) bits.push(s.location.section);
  if (s.location.page !== undefined) bits.push(`page ${s.location.page}`);
  return bits.join(", ") || "n/a";
}

export function renderReviewChecklist(ev: EvidenceMap): string {
  const lines: string[] = [];
  lines.push(`# ${ev.company} — Review Checklist`);
  lines.push("");
  lines.push(`> ${ev.label} · Draft for review`);
  lines.push("");
  lines.push(`Workflow: ${ev.workflow} v${ev.workflow_version} · as of ${ev.as_of}`);
  lines.push("Review status: draft_for_review — reviewer_decision is null on every claim until sign-off.");
  lines.push("");
  const flagged = ev.claims.filter((c) => FLAGGED_STATUSES.includes(c.review_status));
  lines.push(`## Figures to verify (${flagged.length} flagged)`);
  lines.push("");
  const groups: Array<[ReviewStatus, string]> = [
    ["needs_analyst", "Needs analyst review"],
    ["flagged", "Flagged"],
    ["unresolved", "Unresolved"],
  ];
  for (const [status, title] of groups) {
    const items = flagged.filter((c) => c.review_status === status);
    if (items.length === 0) continue;
    lines.push(`### ${title}`);
    lines.push("");
    for (const c of items) {
      const srcs = c.sources.map((s) => `${s.source_id} (${mdSourceLocation(s)})`).join(", ");
      lines.push(`- [ ] **${c.claim_id}** — "${c.rendered_text}" (relationship: ${c.relationship}; sources: ${srcs})`);
      if (c.review_note) lines.push(`  - What to verify: ${c.review_note}`);
    }
    lines.push("");
  }
  lines.push("## Standing checks (enforced automatically on every run)");
  lines.push("");
  for (const check of loadChecklist()) {
    lines.push(`- ${check.name} (\`${check.id}\`)`);
  }
  lines.push("");
  lines.push("## Excluded sources");
  lines.push("");
  for (const s of ev.excluded_sources) {
    lines.push(`- ${s.source_id} — ${s.title}: ${s.exclusion_reason ?? "excluded"}`);
  }
  lines.push("");
  lines.push(`## Sources reviewed (${ev.summary.sources_reviewed})`);
  lines.push("");
  const seen = new Set<string>();
  for (const c of ev.claims) {
    for (const s of c.sources) {
      if (seen.has(s.source_id)) continue;
      seen.add(s.source_id);
      lines.push(`- ${s.source_id} — ${s.title} (${s.source_type}; ${mdSourceLocation(s)})`);
    }
  }
  lines.push("");
  lines.push(
    "Cell-level lineage applies to the Excel-sourced figures only; filing, transcript, note, and CSV references are section- or page-level. All data is synthetic.",
  );
  lines.push("");
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Run record
// ---------------------------------------------------------------------------

export function buildRunRecord(ev: EvidenceMap): Record<string, unknown> {
  const wf = loadWorkflowMeta();
  const usedIds = new Set(ev.claims.flatMap((c) => c.source_ids));
  return {
    label: LABEL,
    workflow: wf.name,
    workflow_version: wf.version,
    as_of: ev.as_of,
    review_status: "draft_for_review",
    retrieval: { mode: "static", network_access: "none", credentials_required: false },
    determinism_note:
      "All source data is committed fixture content with static as-of dates; no wall-clock timestamps are embedded, so re-runs produce identical JSON/HTML/Markdown artifacts. Tool versions below reflect the environment that produced this record.",
    inputs: INPUT_FILES.map((f) => ({ file: f, sha256: sha256(p(f)) })),
    template: { file: "template/ic-memo-template.docx", sha256: sha256(p("template/ic-memo-template.docx")) },
    fixtures: ["fixtures/sources.json", "fixtures/memo-content.json"].map((f) => ({ file: f, sha256: sha256(p(f)) })),
    sources_used: ev.claims
      .flatMap((c) => c.sources)
      .filter((s, i, all) => all.findIndex((x) => x.source_id === s.source_id) === i)
      .map((s) => ({ source_id: s.source_id, title: s.title, location: mdSourceLocation(s), used: usedIds.has(s.source_id) })),
    sources_excluded: ev.excluded_sources.map((s) => ({
      source_id: s.source_id,
      title: s.title,
      reason: s.exclusion_reason ?? "excluded",
    })),
    figures_flagged: ev.claims
      .filter((c) => FLAGGED_STATUSES.includes(c.review_status))
      .map((c) => ({ claim_id: c.claim_id, review_status: c.review_status })),
    unresolved_items: ev.claims
      .filter((c) => c.review_status === "unresolved")
      .map((c) => ({ claim_id: c.claim_id, rendered_text: c.rendered_text, note: c.review_note ?? "" })),
    tool_versions: { officecli: officecliVersion(), node: process.version },
    artifacts: [
      OUTPUT.docx,
      OUTPUT.evidenceJson,
      OUTPUT.evidenceHtml,
      OUTPUT.reviewChecklist,
      OUTPUT.reviewChecklistHtml,
      OUTPUT.runRecord,
      OUTPUT.provenanceHtml,
    ],
  };
}

export function writeArtifacts(ev: EvidenceMap): void {
  fs.writeFileSync(p(OUTPUT.evidenceJson), JSON.stringify(ev, null, 2) + "\n");
  fs.writeFileSync(p(OUTPUT.evidenceHtml), renderEvidenceHtml(ev));
  fs.writeFileSync(p(OUTPUT.reviewChecklist), renderReviewChecklist(ev));
  fs.writeFileSync(p(OUTPUT.reviewChecklistHtml), renderReviewChecklistHtml(ev));
  fs.writeFileSync(p(OUTPUT.runRecord), JSON.stringify(buildRunRecord(ev), null, 2) + "\n");
}

/** Written after the acceptance checks so the page can carry real pass states. */
export function writeProvenance(ev: EvidenceMap, outcomes: CheckOutcome[]): void {
  fs.writeFileSync(p(OUTPUT.provenanceHtml), renderProvenanceHtml(ev, outcomes));
}
