/**
 * Evidence Tracker — session-scoped accumulator for live lineage.
 *
 * The tracker lives on the Agent instance and accumulates sources and
 * claims as the agent drafts an Office document. When the agent calls
 * `evidence finalize`, the tracker writes Evidence.json (and optionally
 * a Run_Record.json) alongside the document.
 *
 * Design principles:
 * - The tracker is NOT a silent observer — every register/record call
 *   is visible to the user through the tool result.
 * - The tracker is session-scoped: one tracker per agent prompt cycle.
 * - The schema matches the flagship example so the GUI can render both.
 * - The checker can call `validateEvidence()` to reject unsourced
 *   quantitative figures before the document is marked done.
 */

import * as fs from "fs";
import * as path from "path";
import { createHash } from "crypto";
import {
  type EvidenceModel,
  type SourceRecord,
  type ClaimRecord,
  type RunRecord,
} from "./model.js";
import { readEvidenceFile, validateEvidenceModel } from "./validator.js";

export class EvidenceFinalizationError extends Error {
  constructor(
    public readonly validation: {
      valid: boolean;
      problems: string[];
      summary: string;
    },
  ) {
    super(`Evidence finalization blocked: ${validation.problems.join("; ")}`);
    this.name = "EvidenceFinalizationError";
  }
}

export class EvidenceTracker {
  private sources: Map<string, SourceRecord> = new Map();
  private claims: Map<string, ClaimRecord> = new Map();
  private excludedSources: Map<string, string> = new Map(); // source_id → reason
  private inputFiles: Map<string, string> = new Map(); // file → sha256
  private workflowName: string = "live-drafting";
  private workflowVersion: string = "1.0.0";
  private company: string = "";
  private title: string = "";
  private subtitle: string = "";
  private asOf: string = "";
  private label: string = "Draft — generated by Quiver agent";
  private finalized: boolean = false;

  // ─── Source Management ──────────────────────────────────────────────

  registerSource(source: SourceRecord): {
    source_id: string;
    registered: boolean;
  } {
    if (this.finalized) {
      return { source_id: source.source_id, registered: false };
    }
    if (!source.approved && source.exclusion_reason) {
      this.excludedSources.set(source.source_id, source.exclusion_reason);
    }
    this.sources.set(source.source_id, source);
    return { source_id: source.source_id, registered: true };
  }

  excludeSource(sourceId: string, reason: string): { source_id: string; excluded: boolean } {
    if (this.finalized) {
      return { source_id: sourceId, excluded: false };
    }
    const src = this.sources.get(sourceId);
    if (src) {
      src.approved = false;
      src.exclusion_reason = reason;
    }
    this.excludedSources.set(sourceId, reason);
    return { source_id: sourceId, excluded: true };
  }

  /**
   * Human/VP promote: only this path (or fixture/API callers) may set
   * approved:true. The maker tool must not self-approve.
   */
  approveSource(sourceId: string): { source_id: string; approved: boolean } {
    if (this.finalized) {
      return { source_id: sourceId, approved: false };
    }
    const src = this.sources.get(sourceId);
    if (!src) {
      return { source_id: sourceId, approved: false };
    }
    src.approved = true;
    delete src.exclusion_reason;
    this.excludedSources.delete(sourceId);
    return { source_id: sourceId, approved: true };
  }

  // ─── Claim Management ───────────────────────────────────────────────

  recordClaim(claim: ClaimRecord): { claim_id: string; recorded: boolean } {
    if (this.finalized) {
      return { claim_id: claim.claim_id, recorded: false };
    }
    this.claims.set(claim.claim_id, claim);
    return { claim_id: claim.claim_id, recorded: true };
  }

  updateClaimStatus(
    claimId: string,
    reviewStatus: ClaimRecord["review_status"],
    reviewNote?: string,
  ): { claim_id: string; updated: boolean } {
    const claim = this.claims.get(claimId);
    if (!claim) return { claim_id: claimId, updated: false };
    claim.review_status = reviewStatus;
    if (reviewNote !== undefined) claim.review_note = reviewNote;
    return { claim_id: claimId, updated: true };
  }

  // ─── Input File Tracking ────────────────────────────────────────────

  // M4: async so a large input file doesn't block the event loop while
  // hashing (every other file op in the codebase uses fs.promises).
  async registerInput(file: string): Promise<{ file: string; sha256: string | null }> {
    try {
      const abs = path.resolve(file);
      const buf = await fs.promises.readFile(abs);
      const hash = createHash("sha256").update(buf).digest("hex");
      this.inputFiles.set(file, hash);
      return { file, sha256: hash };
    } catch {
      return { file, sha256: null };
    }
  }

  // ─── Metadata ───────────────────────────────────────────────────────

  setMetadata(meta: {
    workflow?: string;
    company?: string;
    title?: string;
    subtitle?: string;
    asOf?: string;
  }): void {
    if (meta.workflow) this.workflowName = meta.workflow;
    if (meta.company) this.company = meta.company;
    if (meta.title) this.title = meta.title;
    if (meta.subtitle) this.subtitle = meta.subtitle;
    if (meta.asOf) this.asOf = meta.asOf;
  }

  // ─── Validation ─────────────────────────────────────────────────────

  /**
   * Validate that every quantitative claim has at least one approved
   * source OR is flagged/unresolved. Returns a list of problems.
   * This is the live counterpart to the flagship example's
   * `claims-have-sources` acceptance check.
   */
  validateEvidence(): { valid: boolean; problems: string[]; summary: string } {
    const problems: string[] = [];
    if (this.claims.size === 0) {
      problems.push("evidence must contain at least one recorded claim");
    }
    if (this.sources.size === 0) {
      const allExplicitlyUnresolved =
        this.claims.size > 0 &&
        [...this.claims.values()].every(
          (c) =>
            c.relationship === "unresolved" ||
            c.review_status === "flagged" ||
            c.review_status === "unresolved",
        );
      if (!allExplicitlyUnresolved) {
        problems.push("evidence must contain at least one registered source");
      }
    }
    const approvedSourceIds = new Set(
      [...this.sources.values()].filter((s) => s.approved).map((s) => s.source_id),
    );
    // Explicitly excluded only — unapproved/pending is NOT the same as excluded.
    const excludedSourceIds = new Set(this.excludedSources.keys());

    for (const claim of this.claims.values()) {
      const isExplicitlyUnresolved =
        claim.relationship === "unresolved" ||
        claim.review_status === "flagged" ||
        claim.review_status === "unresolved";
      if (claim.source_ids.length === 0 && !isExplicitlyUnresolved) {
        problems.push(`${claim.claim_id} has no source references and is not marked unresolved`);
      }
      for (const sourceId of claim.source_ids) {
        if (!this.sources.has(sourceId)) {
          problems.push(`${claim.claim_id} references missing source ${sourceId}`);
        }
      }
      // Check for excluded source references
      for (const srcId of claim.source_ids) {
        if (excludedSourceIds.has(srcId)) {
          problems.push(`${claim.claim_id} cites an excluded source (${srcId})`);
        }
      }

      if (!claim.is_quantitative) continue;

      const hasApprovedSource = claim.source_ids.some((id) => approvedSourceIds.has(id));
      const isFlagged = claim.review_status === "flagged" || claim.review_status === "unresolved";

      if (!hasApprovedSource && !isFlagged) {
        problems.push(`${claim.claim_id} has no approved source and is not flagged/unresolved`);
      }
    }

    const totalClaims = this.claims.size;
    const quantClaims = [...this.claims.values()].filter((c) => c.is_quantitative).length;
    const flaggedClaims = [...this.claims.values()].filter(
      (c) => c.review_status === "flagged" || c.review_status === "unresolved",
    ).length;

    const summary = `${totalClaims} claims (${quantClaims} quantitative), ${flaggedClaims} flagged/unresolved, ${this.sources.size} sources (${this.excludedSources.size} excluded)`;

    return {
      valid: problems.length === 0,
      problems,
      summary,
    };
  }

  // ─── Finalize & Write ────────────────────────────────────────────────

  /**
   * Write Evidence.json (and optionally Run_Record.json) to the output
   * directory alongside the Office document. Returns the paths written.
   */
  finalize(
    outputDir: string,
    docFileName?: string,
    options?: { requireValidEvidence?: boolean },
  ): {
    evidencePath: string;
    runRecordPath: string | null;
    validation: { valid: boolean; problems: string[]; summary: string };
  } {
    const validation = this.validateEvidence();
    if (options?.requireValidEvidence !== false && !validation.valid) {
      throw new EvidenceFinalizationError(validation);
    }

    const now = new Date().toISOString();
    const dateLine = `${this.asOf || now.split("T")[0]} · ${this.label} · Draft for review`;

    const model: EvidenceModel = {
      label: this.label,
      workflow: this.workflowName,
      workflow_version: this.workflowVersion,
      company: this.company,
      as_of: this.asOf || now.split("T")[0],
      title: this.title,
      subtitle: this.subtitle,
      date_line: dateLine,
      claims: [...this.claims.values()],
      sources: [...this.sources.values()],
      sources_excluded: [...this.excludedSources.entries()].map(([source_id, reason]) => ({
        source_id,
        reason,
      })),
      review_status: "draft_for_review",
      generated_at: now,
      generated_by: "live_agent",
    };
    const shape = validateEvidenceModel(model);
    if (!shape.valid) {
      throw new EvidenceFinalizationError({
        valid: false,
        problems: shape.problems,
        summary: "Generated evidence did not satisfy the persisted schema",
      });
    }

    const baseName = docFileName ? docFileName.replace(/\.(docx|xlsx|pptx)$/, "") : "Document";
    const evidenceFileName = `${baseName}_Evidence.json`;
    const runRecordFileName = `${baseName}_Run_Record.json`;

    fs.mkdirSync(outputDir, { recursive: true });
    const evidencePath = path.join(outputDir, evidenceFileName);
    fs.writeFileSync(evidencePath, JSON.stringify(model, null, 2), "utf8");

    // Write run record
    const runRecord: RunRecord = {
      workflow: this.workflowName,
      workflow_version: this.workflowVersion,
      review_status: "draft_for_review",
      generated_at: now,
      inputs: [...this.inputFiles.entries()].map(([file, sha256]) => ({
        file,
        sha256,
      })),
      sources_excluded: [...this.excludedSources.entries()].map(([source_id, reason]) => ({
        source_id,
        reason,
      })),
    };

    const runRecordPath = path.join(outputDir, runRecordFileName);
    fs.writeFileSync(runRecordPath, JSON.stringify(runRecord, null, 2), "utf8");

    this.finalized = true;

    return { evidencePath, runRecordPath, validation };
  }

  // ─── Reset (for new drafting cycles) ─────────────────────────────────

  reset(): void {
    this.sources.clear();
    this.claims.clear();
    this.excludedSources.clear();
    this.inputFiles.clear();
    this.company = "";
    this.title = "";
    this.subtitle = "";
    this.asOf = "";
    this.finalized = false;
  }

  // ─── Getters ─────────────────────────────────────────────────────────

  getSources(): SourceRecord[] {
    return [...this.sources.values()];
  }

  getClaims(): ClaimRecord[] {
    return [...this.claims.values()];
  }

  getExcludedSources(): Array<{ source_id: string; reason: string }> {
    return [...this.excludedSources.entries()].map(([source_id, reason]) => ({
      source_id,
      reason,
    }));
  }

  isFinalized(): boolean {
    return this.finalized;
  }
}

/**
 * Validate a document's companion evidence file and its source/claim rules.
 * This is shared by the checker and GUI review flow so neither can silently
 * accept a different interpretation of Evidence.json.
 */
export async function validateEvidenceFile(documentPath: string): Promise<{
  valid: boolean;
  missing: boolean;
  evidencePath: string;
  problems: string[];
  model?: EvidenceModel;
}> {
  const loaded = await readEvidenceFile(documentPath);
  if (!loaded.valid || !loaded.model) {
    return {
      valid: false,
      missing: loaded.missing,
      evidencePath: loaded.evidencePath,
      problems: loaded.problems,
    };
  }

  const tracker = new EvidenceTracker();
  for (const source of loaded.model.sources) tracker.registerSource(source);
  for (const claim of loaded.model.claims) tracker.recordClaim(claim);
  const semantic = tracker.validateEvidence();
  return {
    valid: semantic.valid,
    missing: false,
    evidencePath: loaded.evidencePath,
    problems: semantic.problems,
    model: loaded.model,
  };
}
